### ISSUE TITLE
Bug in emp::Ptr (assignment operator?)

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#143]
In the scenario demonstrated in the following test case, running testB::RunBFun() fails to correctly store the return of testB::b_fun in testB::b (instead, b remains uninitialized). If I use normal C++ pointers instead, this works fine. I assume it's some bug in the assignment operator?

It's possible that this example is more complex than it needs to be to demonstrate this behavior - this is just the form I encountered it in.

```
TEST_CASE("Replicate ptr bug", "[ptr]") {
  struct testA {
    int a = 9;
    emp::Ptr<int> GetA() {return emp::ToPtr(&a);}
  };

  struct testB {
    std::function<emp::Ptr<int>(void)> b_fun;
    emp::Ptr<int> b;
    
    void SetBFun(std::function<emp::Ptr<int>(void)> fun) {
      b_fun = fun;
    }

    void RunBFun() {
      b = b_fun();
    }

  };

  testA ta;
  testB tb;
  
  std::function<emp::Ptr<int>(void)> return_a = [&ta](){return ta.GetA();};
  tb.SetBFun(return_a);
  tb.RunBFun();
  REQUIRE(*(tb.b) == 9); // Fails with assert error for dereferencing null pointer

}
```

**Comment by mercere99** [comment]
Well... this is going to be an annoying one to debug.  On my machine the REQUIRE passes (and indeed prints '9' when I add a cout)

**Comment by mercere99** [comment]
I tried it with both GCC 7.1 and Clang 9.0

**Comment by mercere99** [comment]
Okay -- I'm lying.  The result above was when I tested it in isolation.  When I incorporate it into test_base.cc, I get:

```
-------------------------------------------------------------------------------
Replicate ptr bug
-------------------------------------------------------------------------------
test_base.cc:475
...............................................................................

test_base.cc:475: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:   5 |   4 passed | 1 failed
assertions: 205 | 204 passed | 1 failed
```

**Comment by mercere99** [comment]
Here's a simplified version of the unit test that still fails:

```
TEST_CASE("Replicate ptr bug", "[base]")
{
  int a = 9;

  emp::Ptr<int> ptr_a;
  ptr_a = emp::ToPtr(&a);

  int a_val = *(ptr_a);
  REQUIRE(a_val == 9);
}
```
Note that simplifying the middle block to combine the two lines so that it is set in the constructor eliminates the problem (so it must have something to do with constructing an empty pointer and then copying into it.)

```
  emp::Ptr<int> ptr_a = emp::ToPtr(&a);
```

**Comment by mercere99** [comment]
So, the problem turned out to be that I was giving the ID of -1 to everything that shouldn't be tracked.  I had and error in the move constructor where I indicated that a move didn't need to happy if the ID's matched, but it should actually have checked the pointers.

In the case of Emily's example, we were creating a non-assigned Ptr object with ID of -1 and a null pointer.  The emp::ToPtr() function then took a pointer from a pre-existing object (hence one it shouldn't track to make sure it's deleted properly) and tried to move it to the pointer object.  The pointer object saw the IDs were the same (both -1), so it didn't bother copying the pointer value over and left it as -1.

Outside of tracking memory, this all worked perfectly.  It was just the debug tools that were messing things up and they're fixed now.  The new test is in place and passing.
