### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#16]
Not sure how close we are to feeling ready for any sort of release but thought it'd be good to start the conversation.

[Semantic versioning](http://semver.org/) has always seemed like a sensible option to me, though again I'm not sure what the opinions on versioning/releases are.

I feel like this + licenses + docs would be the primary blocks between where we are now and being considered 'usable' by outsiders (in my admittedly highly limited experience).

cc @mercere99 thoughts?

**Comment by mercere99** [comment]
Semantic versioning makes sense to me, though the one thing it misses is breaks in consistency.  I think that's okay for a library in a way that I would be less comfortable for a software package, but I'm still iffy about it and feel like there should be some way to signify.

What I mean by this is sometimes you can have complete compatibility of all settings, etc, but because you take random numbers in a different order, if you redo runs with the same random number see you'll get quantitatively different results (though they should be qualitatively the same).

In Avida we use something similar Semantic versioning, but aren't great about updating the middle number and usually just update the last.

**Comment by bocajnotnef** [comment]
Is there a specific set of things that we feel should be accomplished before christening the initial version of Empirical, or do we just want to arbitrarily say "This is the initial version and it's not a big deal"?

**Comment by mercere99** [comment]
I'm starting to work on a "release blog post" that we step people though a simple use of Empirical.  This has already been leading to some fixes; I think as soon as the blog post is ready (and tested by a few others), we'll lock in that version of Empirical as the first alpha release (0.1.0?)

**Comment by bocajnotnef** [comment]
Alright, excellent.

**Comment by bocajnotnef** [comment]
just noting that versioning is now a thing;

use `git describe` to get current version:
`v release . major . minor-#sinceLastRelease-currCommit`

**Comment by emilydolson** [comment]
In light of versioning having been a thing for three years now, I'm going to go ahead and close this. We should still figure out what we want before we're willing to make a 0.1.0 release, but my assumption at this point is that that will pretty much happen when we release MABE 2.0.

**Comment by mercere99** [comment]
It is also completely fair to bump versioning every time someone (in the group) locks in another software package to a version.  Once we officially go public with Empirical, though, we're going to need to be a lot more careful and bump the version with every released change.
