### ISSUE TITLE
Transfer Empirical to Devosoft....?

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#17]
Current questions:

What's the best way to do this? A direct transfer of ownership from @mercere99 to Devosoft? Forking @mercere99's repo into Devosoft? Making an empty Devosoft repo and pushing a copy of Empirical up to it?

@emilydolson @nahumj Thoughts?

**Comment by emilydolson** [comment]
A direct transfer seems like the most straightforward solution. Forking it would work too, but I think the only benefit would be making it more obvious that @mercere99 was the one who started it. Making an empty repo and pushing Devosoft into it seems like it would just be a more cumbersome version of forking it, but I could be overlooking something.

**Comment by mercere99** [comment]
Forking has the disadvantage that it would always point to the one in mercere99 as the original, which might get confusion.  A direct transfer removes all trace from mercere99, which I think is fine.  In thumbing around, my confusion is why so many repositories (such as Emscripten itself!) are still in user accounts rather than organizations.  I just want to make sure we're not missing something.

**Comment by emilydolson** [comment]
That is a good question, but I can't find any downsides. And there are
plenty of repositories of a similar scale to what we plan for Empirical to
be that are managed via organizations (a quick survey of the Python
libraries I use most often only turned up one that is owned by an
individual rather than an organization). It's also possible that this
doesn't come up that frequently - you can do a lot just by giving people
write permissions. Integrating third party services is pretty much the only
thing that would require you to be an actual owner.

**Comment by mercere99** [comment]
It also looks like we should move ahead with it then, so fine by me.  Here's one account of such a move: https://blog.kevin-brown.com/github/2015/01/15/transferring-repositories-cleanly-on-github.html , and another, older one: http://www.codelord.net/2012/03/31/migrating-to-a-github-organization/

**Comment by bocajnotnef** [comment]
+1 to migrating

Making a list of things to do after migration in #24

**Comment by bocajnotnef** [comment]
blocking:
 - [ ] make sure everyone has everything checked in to the remote
 - [ ] make a solid backup of the repo in case things explode
 - [ ] do transfer--probably fri 11/20/15

**Comment by mercere99** [comment]
Moved!
