### ISSUE TITLE
SettingConfig scope issue

### ISSUE THREAD

**Issue by chavez-ju** [devosoft/Empirical#315]
Within the SettingConfig class, adding a new setting to a config object requires an already initialized variable to be used in order for a pointer to be established to that variable within SettingInfo. This can pose issues in the case that a config is used out of scope from where settings were added. A possible solution is to create a deep copy of those variables inside the config rather than establishing a pointer to the initialized variables.

**Comment by emilydolson** [comment]
Upon further examination, this turns out to be a way simpler fix than I expected. The already initialized variable was already optional for both the `SettingInfo` constructor and `ComboSettingInfo` constructor. The `AddComboSetting` method already had a version that didn't require a pre-initialized variable, so I created a parallel version of the `AddSetting` method that also doesn't.

**Comment by emilydolson** [comment]
I'm going to go ahead and close this because this issue ended up being more elaborate than this and it is fixed in #414
