### ISSUE TITLE
Where does Evolve/bloom_filter.h belong?

### ISSUE THREAD

**Issue by amlalejini** [devosoft/Empirical#399]
bloom_filter.h doesn't look like it's specific to evolution-related stuff (looks like a fancy data structure to me!). Also, it's copied from elsewhere, so should it actually go in third-party? 

In the reorganization PR, it is a little out of place in the include/emp/ directory (as it's not in the emp namespace).

**Comment by mercere99** [comment]
I assume this came in with the Systematics PR?  It is a useful data structure and I'd be happy to have it in datastruct/ if it's supposed to be there are all.  @emilydolson  and I are actually teaching about bloom filters in class this semester; I'm guessing that she'd know more about what to do with it.

**Comment by amlalejini** [comment]
datastructs makes sense as the place to put it if it stays in the include/emp/ directory. It's copied (legitimately) from a different library(?), so it's not currently in the emp namespace.  Should we stick it in the emp namespace? Or should it actually be in third-party?

**Comment by mercere99** [comment]
What license was it under?  As long as it's compatible for inclusion with modification (and well written), we could do so.  Probably with substantial cleanup to bring it more in line.

**Comment by amlalejini** [comment]
From the bloom_filter header:
```
/*
 *********************************************************************
 *                                                                   *
 *                           Open Bloom Filter                       *
 *                                                                   *
 * Author: Arash Partow - 2000                                       *
 * URL: http://www.partow.net                                        *
 * URL: http://www.partow.net/programming/hashfunctions/index.html   *
 *                                                                   *
 * Copyright notice:                                                 *
 * Free use of the Open Bloom Filter Library is permitted under the  *
 * guidelines and in accordance with the MIT License.                *
 * http://www.opensource.org/licenses/MIT                            *
 *                                                                   *
 *********************************************************************
*/
```

**Comment by amlalejini** [comment]
As the moment, my instinct is to stick it in the emp namespace, move it to emp/include/datastructs/, add a comment that it's adapted from the original source, and file an issue to update it to be more in line with Empirical styling/improve functionality (if necessary). 

@emilydolson what do you think?

**Comment by emilydolson** [comment]
I think that sounds like a good plan! For the sake of record-keeping, it is from here: https://github.com/ArashPartow/bloom

**Comment by mercere99** [comment]
It occurs to me that I don't know the etiquette of modifying someone's code under the MIT license (i.e., how to properly indicate it is a modification while giving credit to the original), BUT if we're going to use this class we should convert it to the emp namespace (since we don't want to include anything out of namespace protection) and shift it to Empirical style.

**Comment by emilydolson** [comment]
My understanding is that the etiquette is to provide attribution as clearly as possible, with links to the original version. It should be made very clear in comments in the file itself so that anyone who is further modifying our version can continue to provide proper attribution. Ideally it would be great if it were also made clear to library users that aren't specifically looking at this Bloom filter file. The best we can do there is probably to also put attribution in the documentation. 

Ideally we'd have a nifty citation management system like R does where you can just ask Empirical to give you the citations for all the code that you're using (both for code and methodology). but obviously we're not there yet. And that starts to raise more complex questions about code citation that it's probably not worth delving into here.

**Comment by ArashPartow** [comment]
Should be ok to wrap the entire class in your specific emp namespace.

**Comment by emilydolson** [comment]
Oh wow, thanks for weighing in @ArashPartow! And thanks for writing such a great Bloom filter implementation! I have found it very helpful in my research and my students have enjoyed using it in class.

**Comment by emilydolson** [comment]
As of #418, it is incorporated into the emp namespace (with a couple tweaks for stylistic consistency).
