### ISSUE TITLE
Why rely on Jquery?

### ISSUE THREAD

**Issue by LTLA** [devosoft/Empirical#511]
(Part of openjournals/joss-reviews#6617)

It seems like some of the C++ calls are converted into Javascript code that uses Jquery (see the various `$(...)` calls in `include/emp/web`). Is this really necessary? It adds a Jquery dependency to all downstream web applications that might not otherwise use it. From what I see, many of the Jquery calls in this library involve manipulating with DOM elements, so why not just use vanilla javascript (e.g., `document.getElementById`)?

In any case, if you really do need Jquery, this should be explicitly documented somewhere. I didn't see it discussed in any obvious place in the documentation.

**Comment by mercere99** [comment]
You are correct -- Jquery seemed like it was going to be a big help when we first started using it in Empirical, but none of the functionality it provides is critical anymore, especially since we are working with auto-generated JavaScript code.  We have planned to remove it for a while now and need to escalate the priority of that improvement to reduce the dependencies.

**Comment by mmore500** [comment]
Opened PR #512 for this.

**Comment by mmore500** [comment]
Fixed in #512 !
