### ISSUE TITLE
emp::BitSet endian-ness

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#62]
Currently, indices into emp::BitSet are in big endian (i.e. Bitset[0] is the right-most bit). This makes sense when thinking of a BitSet as a binary number, but it's confusing when using a BitSet as an organism (or just as a container for a sequence of 1s and 0s). Is this desired behavior? If so, we should probably add an explanatory note.

**Comment by mercere99** [comment]
Right now emp::BitSet is implemented as a drop-in replacement for std::bitset, which also has bit 0 on the right.  Since these are also the same as bit patterns in integral types, it means standard bit-magic algorithms will work on BitSets without confusing modification.

I did update the note at the top to briefly explain this.
