### ISSUE TITLE
Indexing into World fails when population is not full

### ISSUE THREAD

**Issue by emilydolson** [devosoft/Empirical#68]
PopulationManager_Grid places organisms without parents randomly. As such, it is challenging to guarantee that a population in a grid is fully initialized. Once we start allowing organisms to die, there will probably be many more reasons that there might be empty spaces within a population. Currently, since indexing into a world with the [] operator grabs the organism in that location and de-references the pointer, populations that have gaps in them automatically cause a segfault, because a null pointer is de-referenced.

I can think of a few solutions:
- Make the [] operator in World.h check whether the pointer is null before de-referencing it, and return some sort of empty organism if it is. Problem: Every org type would need to have an agreed-upon null version, and every program dealing with worlds would need to be aware of this eventuality.
- Always initialize worlds to contain some sort of null organism (and replace any dead orgs with it too). This has the same problem of needing to define a null organism, but it saves a comparison in the [] operator.
- Make worlds iterable, and define the iteration behavior such that they skip over null organisms. This is potentially less flexible (maybe someone really just wants to know what the 10th org is), but is very clean.

There are probably other options that I'm not thinking of. Thoughts?

**Comment by mercere99** [comment]
As a (poor) stopgap, I had added IsOccupied() to World, but clearly we need a better solution.

For suggestion 1 above, we could allow classes with a static null_org to always use that when put into a world (if it exists); otherwise the population will try to use the default constructor to create an organism (which for numerical values will be, I believe zero, but if not we can make it so).  Only if neither of these is possible should it crash, although a nice warning would be good in such cases.  ;-)

I think indexing in will need to be common, so iterable still leaves a reasonably large problem.

A fourth option would be for operator[]  to return a pointer to an organism, but I think this will be annoying in most cases.

**Comment by emilydolson** [comment]
It seems like, for a lot of organism types (e.g. bitset), the default constructor would create something that isn't distinguishable from a viable organism. We can't even guarantee that it will have a fitness of 0. This seems like a problem, since usually when there are empty spaces in a population, we want them there. Is there a reason that we shouldn't be concerned about that?

**Comment by mercere99** [comment]
In many cases we want to have organisms that are distinct from their genome, but not in any of the cases we've looked at thusfar.  What if we create organism objects that deal with this sort of situation, that that's what you get when you index into the world?  Then we have a null organism object, but normally you can always use org.genome if you want to access the underlying genome.

I started to build some code along these lines (in the org manager) and suspect I should get back to finishing that.  The goal there would be to automatically identify the org/genome pair, but infer them (or create them) when they are not declared explicitly.

**Comment by mercere99** [comment]
I agree that the null organism is the way to go in the longer term; with iterators working well and the ability to check occupied, access pointers, and fail with proper asserts, I'm going to mark this original issue closed.
