### ISSUE TITLE
Examine travis CI caching of emscripten SDK

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#93]
Examine the possibility of using the caching ability of Travis to compile/hold the emscripten SDK so we can run those tests.

**Comment by emilydolson** [comment]
For progress I've made so far on getting Emscripten working on Travis, see the visualization branch of my fork.

**Comment by emilydolson** [comment]
Update: It works! Caching may still be the better solution in the long run, but we've got a workable solution  for automatically running emscripten tests.

**Comment by mercere99** [comment]
If this now works, should we close this issue?

**Comment by emilydolson** [comment]
The solution that we currently have is probably inferior to actually using Travis's caching. So I guess it depends on how much we care about the marginal difference.

**Comment by mercere99** [comment]
How big is the marginal difference?

**Comment by emilydolson** [comment]
I have no clue. It might be purely aesthetic, or there could be some sort of speed or maintainability benefit.

**Comment by emilydolson** [comment]
I would tend to think it's a low priority.

**Comment by mercere99** [comment]
Got it!

**Comment by emilydolson** [comment]
Okay, so I finally looked into this. It looks like using caching requires that it's possible to do all of the setup on Travis once, after which it is cached. That won't work in this case because building Emscripten will time out. So I'm going to go ahead and close this, but it is worth keeping in mind that our current solution is inelegant and it would be great if we happened upon a better one.
