### ISSUE TITLE
Switch license from MIT to Apache

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#95]
Apache grants patent freedom--MIT has potential for scumminess.

**Comment by mercere99** [comment]
Apache also looks like it has some annoying requirements.  For example, it requires you to explicitly list out all the modifications that you’ve done in the original software if you do release your modified software, and that's just annoying.

We could try to find another patent-aware license, but the one other issue that I can't seem to find any information about is HOW the patent rights are handled without doing full patent research.  For example, if I grant all patent rights to someone using my software, but it turns out that I accidentally did something that was patented by someone else, doesn't any third party get in just as much trouble?  Only then they sue the writers of the library for claiming to release patent rights...

I *know* that we have all the correct copyrights, but its always going to be unclear about patent rights.  Since I don't think we're doing anything patentable (let alone actually patented), my inclination at this point is to stick with MIT.

**Comment by mercere99** [comment]
MIT License is very much the standard and I don't think we should switch away.  Closing issue for now.
